### PR TITLE
Allow path in influxdb url

### PR DESCRIPTION
**Pull request by rsertelon**
Hi,

We are using influxdb behind a reverse proxy. This pull request aims at allowing us (or anyone in our case) to use your library to send data to our influxdb server.

Also, I've fixed a compilation problem for java 1.7.

Regards,

### CODE REVIEW

**Comment by davidB** [comment]
Thanks.

**Comment by rsertelon** [comment]
Thank you ;) Do you plan to release soon?

**Comment by davidB** [comment]
I can release next WE. ping me, next week, sometimes I forgot ;-)

**Comment by rsertelon** [comment]
Thanks for the release, much appreciated ;)

**Comment by rsertelon** [comment]
The artifact for 0.7.0 is not in Central. But I see you made the release, maybe you forgot to publish it? :)

**Comment by davidB** [comment]
Right, I forgot about oss.sonatype manual operation, since I used bintray for my new lib/plugins.

Sorry, should be available in the next 24H.

Do you use the new influxdb API ?

**Comment by rsertelon** [comment]
No problem ;)

Not yet, as influxdb 0.9 is not stable yet. We've just started to use the stack ;)

**Pull request merged**
