### PR TITLE
Make HTTP connect timeout and read timeout configurable

### PR DESCRIPTION
**Pull request by nchinmay**
Making HTTP connect timeout and read timeout configurable to reduce occasional SocketTimeoutExceptions thrown while using this reporter.

### CODE REVIEW

**Comment by nchinmay** [comment]
Did I break the travis-ci build?

**Comment by flyhard** [comment]
Nope, not your fault. Gradle has trouble with JDK 7 now...

**Comment by nchinmay** [comment]
@flyhard Thanks for letting me know. I updated my branch to master and the builds pass. I have been using the change I made in the pull request at work and that has helped us solve our SocketTimeoutExceptions issue.

**Comment by davidB** [comment]
Thanks.

**Pull request merged**
