### PR TITLE
add the ms precision to the write URL in HttpInlineSender

### PR DESCRIPTION
**Pull request by liorchen**
According to @cemo suggestion at https://github.com/davidB/metrics-influxdb/issues/30

### CODE REVIEW

**Comment by davidB** [comment]
Thanks

**Comment by liorchen** [comment]
When are you going to release it to the Snapshot?

**Comment by davidB** [comment]
the snapshot should be already available with the instruction of the README. (jitpack.io build version on demand)

**Comment by liorchen** [comment]
great. thanks!

**Pull request merged**
