### PR TITLE
Make the project compatible with Java 7

### LINKED ISSUE #54: Could Support JDK1.7?
Hi:
   The project use jdk8, but our project use jdk1.7. Could you release the bytecode support jdk7?
   Thank you!

### PR DESCRIPTION
**Pull request by emanuelez**
Fixes #54

### CODE REVIEW

**Comment by davidB** [comment]
Thanks, I'll taka a look ASAP this week.

**Comment by emanuelez** [comment]
I've been a bit lazy and included Guava as a testing dependency in order to easily join strings, but I did it the proper way in the non-test code in order not to add a dependency and make the library needlessly bigger.

**Comment by emanuelez** [comment]
I resolved the conflict with `master` that came up after the last merge

**Comment by davidB** [comment]
Thanks

**Pull request merged**
